# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Chris Gmyr
tagline:          'Web Development, Business, and other cool stuff'
url:              http://www.chrisgmyr.com
paginate:         5
paginate_path:    'page/:num/'
baseurl:          /
author:
  name:           Chris Gmyr
  url:            https://twitter.com/cmgmyr
  email:          cmgmyr@gmail.com

pages_list:
  About: '/about'
  Connect: '/connect'
  Projects: '/projects'
  Resume: '/resume'
  Archive: '/archive'
  Feed: 'http://feeds.feedburner.com/chrisgmyr'

follow_me:
  Github: 'https://github.com/cmgmyr'
  Instagram: 'http://instagram.com/cmgmyr'
  LinkedIn: 'http://www.linkedin.com/in/chrisgmyr'
  StackOverflow: 'http://stackoverflow.com/users/1791532/chris-g'
  Twitter: 'https://twitter.com/cmgmyr'