# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Chris Gmyr
tagline:          'Development | Coffee | Life'
url:              http://www.chrisgmyr.com
paginate:         5
paginate_path:    'page/:num/'
baseurl:          /
author:
  name:           Chris Gmyr
  url:            https://twitter.com/cmgmyr
  email:          cmgmyr@gmail.com
timezone:         America/New_York

pages_list:
  About: '/about'
  Connect: '/connect'
  Projects: '/projects'
  Talks: '/talks'
  Resume: '/resume'
  Archive: '/archive'
  Feed: 'http://feeds.feedburner.com/chrisgmyr'

follow_me:
  Github: 'https://github.com/cmgmyr'
  CodeMentor: 'https://www.codementor.io/cmgmyr'
  Instagram: 'http://instagram.com/cmgmyr'
  LinkedIn: 'http://www.linkedin.com/in/chrisgmyr'
  StackOverflow: 'http://stackoverflow.com/users/1791532/chris-g'
  Twitter: 'https://twitter.com/cmgmyr'

gems: [
  'jekyll-paginate',
  'jekyll-gist'
]